language: node_js
node_js:
  - "10"
notifications:
  email: false
before_script:
  - npm install -g abaplint
script:
  - abaplint --version
  - abaplint abaplint.json -f standard --outformat junit --outfile report.xml "src/**/*.*"
branches:
  only: 
    - master
